[package]
name = "gamebox-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
gamebox = { git = "https://github.com/jussyDr/gamebox" }
wgpu = "0.20.0"

[dev-dependencies]
env_logger = "0.11.3"
winit = "0.30.0"
